---
settings:
  name: Licenses and subscriptions
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione sulle licenze e sugli abbonamenti
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Cosa c'è di nuovo
      url: "/whats-new.html"
  - title: Iniziare
    entries:
    - title: Scopri di più
      url: "/concept-licenses-subscriptions.html"
  - title: Licenze d'uso e abbonamenti
    entries:
    - title: Utilizzare la dashboard Panoramica
      url: "/task-homepage.html"
    - title: Gestisci le licenze
      entries:
      - title: Gestisci le licenze dirette
        url: "/task-manage-data-services-licenses.html"
      - title: Gestisci le licenze per Cloud Volumes ONTAP
        entries:
        - title: Licenze basate sulla capacità per Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Licenze basate su nodi per Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Gestisci offerte private
      entries:
      - title: Gestire un'offerta privata AWS
        url: "/task-manage-private-aws.html"
      - title: Gestire un'offerta privata di Azure
        url: "/task-manage-private-azure.html"
      - title: Gestisci un'offerta privata di Google Cloud
        url: "/task-manage-private-google-cloud.html"
    - title: Gestisci gli abbonamenti al Marketplace
      url: "/task-manage-subscriptions.html"
    - title: Gestisci gli abbonamenti Keystone
      url: "/task-manage-keystone.html"
    - title: Conoscenza e supporto
      entries:
      - title: Registrati per ricevere supporto
        url: "/task-support-registration.html"
      - title: Ottieni aiuto
        url: "/task-get-help.html"
    - title: Note legali
      url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
