---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: Gestisci il tuo processo di offerta privata end-to-end generale e specifico per Hyperscaler e le guide di accettazione e attivazione NetApp Intelligent Services per AWS, Azure e Google Cloud. 
---
= Accetta e configura un'offerta privata di AWS Marketplace per la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Accetta un'offerta privata del Marketplace per la NetApp Console nella console AWS e configura le credenziali AWS nella console.

.Prima di iniziare
* Collabora con il reparto vendite NetApp per creare un'offerta privata e ottenere il link di attivazione.
* Assicurati di disporre delle autorizzazioni AWS Marketplace richieste:
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["Visualizzazione e sottoscrizione di un'offerta privata"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["Validazione delle autorizzazioni dell'acquirente"]






== Accetta l'offerta privata nella console AWS

Per attivare l'acquisto e applicare prezzi scontati è necessario completare l'assegnazione dell'abbonamento nella Console.

[NOTE]
====
Devi completare tutti i passaggi per attivare la tua offerta privata. Saltare alcuni passaggi potrebbe causare errori di fatturazione. Accettare e attivare l'offerta più volte comporta un doppio addebito.

====
.Passi
. Fai clic sul collegamento di attivazione dell'offerta privata del tuo team di vendita NetApp . Il collegamento dovrebbe essere simile al seguente:
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
 If you did not receive the link, view private offers in the AWS Marketplace console. The following permissions are required:
+
** Utilizzo di policy gestite da AWS: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions* o *AWSMarketplaceFullAccess*
** Utilizzo di policy IAM personalizzate: `aws-marketplace:ListPrivateListings` E `aws-marketplace:ViewSubscriptions`


. Verrai reindirizzato ad AWS Marketplace per visualizzare l'offerta privata.
+
[NOTE]
====
Le offerte private vengono create in base agli annunci pubblici. Utilizzare il menu a discesa *Selezione offerta* per passare dalle offerte pubbliche a quelle private e viceversa.

====
. Esamina i dettagli dell'offerta privata e verifica che corrispondano al tuo accordo. Se sono errati, non accettarli. Contatta il team del tuo account NetApp .
+
[NOTE]
====
Esistono due tipi di offerte private:

** *Utilizzo su richiesta*
+
*** Informazioni sui prezzi
*** Termini legali


** *Contrarre*
+
*** Durata e date
*** Impostazioni di rinnovo
*** Opzioni contrattuali
*** Prezzo totale del contratto




Per le offerte contrattuali, inserire il numero di unità concordate. Per Cloud Volumes ONTAP, assicurati di selezionare la licenza corretta prima di sottoscrivere l'abbonamento.

====
. Per accettare l'offerta privata, procedi come segue:
+
.. Per l'utilizzo on-demand, clicca su *Iscriviti*.
.. Per le offerte contrattuali, inserisci il numero di unità per ciascun servizio e clicca su *Crea contratto*.


. Dopo l'accettazione, un banner conferma l'iscrizione e fornisce le istruzioni per la registrazione.
. Fai clic su *Configura il tuo account*. Verrà reindirizzato alla NetApp Console per configurare l'abbonamento.
+
[NOTE]
====
Se hai accettato l'offerta ma non hai completato la registrazione, torna alla pagina del prodotto. Per visualizzare l'elenco dei contratti, fare clic su *Visualizza opzioni di acquisto* per visualizzare l'offerta, quindi selezionare *Configura il tuo account*.

====
. Sign in https://console.netapp.com[] con il tuo account Console.
. Dopo aver effettuato l'accesso, vai a https://console.netapp.com/licenses/overview[] . Ti verrà chiesto di:
+
.. Inserisci un *Nome visualizzato* per l'abbonamento al Marketplace.
.. Selezionare gli *Account* della console con accesso all'abbonamento.
.. [Facoltativo] Abilita *Sostituisci abbonamento esistente* per sovrascrivere un abbonamento esistente per un account.
+
[NOTE]
====
*** La sostituzione si applica a un solo account Console.
*** Per associare più account allo stesso abbonamento, configura manualmente gli account aggiuntivi.
*** Se le credenziali non sono mai state associate a un abbonamento, associarle manualmente come descritto nella sezione successiva.


====


. Fare clic su **Associa**.
. Compila il modulo per associare l'abbonamento alla tua organizzazione Console.  Quindi, fare clic su **Associa**.
. Dopo aver associato l'abbonamento, naviga e seleziona la scheda **Preferenze di fatturazione**.
. Esamina le opzioni di abbonamento al marketplace.
. Seleziona l'abbonamento al marketplace che desideri fatturare.  Questo vale solo quando c'è più di un'opzione.
. Seleziona **Salva modifiche**.
. Ripetere questi passaggi secondo necessità, se sono presenti più abbonamenti su più hyperscaler.


Per ulteriori informazioni sugli abbonamenti al marketplace e sulla fatturazione diretta delle licenze, vederelink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentazione sulle preferenze di fatturazione"] .
