= Nuova dashboard Panoramica
:allow-uri-read: 


Il BlueXP digital wallet è stato riprogettato per semplificarne l'utilizzo e ora offre una gestione aggiuntiva di abbonamenti e licenze.



[[new-overview-dashboard]]
=== Nuova dashboard Panoramica

La homepage del portafoglio digitale presenta una dashboard aggiornata delle licenze NetApp e degli abbonamenti Marketplace, con la possibilità di analizzare nel dettaglio servizi specifici, tipi di licenza e azioni richieste.



[[configuring-subscriptions-to-credentials]]
=== Configurazione degli abbonamenti alle credenziali

Il BlueXP digital wallet ora ti consente di configurare i tuoi abbonamenti in base alle credenziali del provider.  Solitamente questa operazione viene eseguita quando si sottoscrive per la prima volta un abbonamento Marketplace o un contratto annuale.  In precedenza la modifica delle credenziali dell'abbonamento poteva essere effettuata solo nella pagina Credenziali.



[[associating-subscriptions-with-organizations]]
=== Associazione degli abbonamenti alle organizzazioni

Ora puoi aggiornare l'organizzazione a cui è associato un abbonamento direttamente dal portafoglio digitale.



[[managing-cloud-volumes-ontap-licenses]]
=== Gestione delle licenze Cloud Volumes ONTAP

Ora gestisci le licenze di Cloud Volumes ONTAP tramite la pagina iniziale o la scheda *Licenze dirette*. Utilizza la scheda *Abbonamenti al Marketplace* per visualizzare le informazioni sul tuo abbonamento.
